[package]
name = "terse"
version = "0.1.0"
authors = ["AdnoC <adam.r.cutler@gmail.com>"]

[dependencies]
# page_size = "0.4.1"
# bit-vec = "0.5.0"
# itertools = "0.7.6"

[dev-dependencies]
compiletest_rs = "*"
